### ISSUE TITLE
Request about "[.]"

### ISSUE THREAD

**Issue by scafroglia93** [hpthreatresearch/iocs#2]
It's possible remove "[.]" from this list please ->
https://raw.githubusercontent.com/hpthreatresearch/iocs/main/dridex/urls.txt

I'd like to integrate the list into my pihole by following your updates directly

**Comment by stoerchl** [comment]
Thanks for reaching out to us. As those are malicious URLs we would rather keep them defaned in our GitHub repository. To integrate our IOCs with various systems we propose to refang the URLs when fetching them. Following GitHub projects could help with that:
- https://github.com/ioc-fang/ioc-fanger
- https://github.com/InQuest/python-iocextract
